/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomInfo: typeof import('./components/BottomInfo.vue')['default']
    HeadNav: typeof import('./components/HeadNav.vue')['default']
    HomeHero: typeof import('./components/HomeHero.vue')['default']
    LayoutBase: typeof import('./components/LayoutBase.vue')['default']
    Menu: typeof import('./components/Menu/src/Menu.vue')['default']
    MenuItem: typeof import('./components/Menu/src/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./components/Menu/src/SubMenu.vue')['default']
  }
}
