/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleBase: typeof import('./components/ArticleListStyles/ArticleBase.vue')['default']
    BaseInfoCard: typeof import('./components/SideLeft/BaseInfoCard.vue')['default']
    BottomInfo: typeof import('./components/BottomInfo.vue')['default']
    HeadNav: typeof import('./components/HeadNav.vue')['default']
    HomeHero: typeof import('./components/HomeHero.vue')['default']
    LatestArticleCard: typeof import('./components/SideLeft/LatestArticleCard.vue')['default']
    LatestArticleList: typeof import('./components/SideLeft/LatestArticleListCard.vue')['default']
    LatestArticleListCard: typeof import('./components/SideLeft/LatestArticleListCard.vue')['default']
    LayoutBase: typeof import('./components/LayoutBase.vue')['default']
    Menu: typeof import('./components/Menu/src/Menu.vue')['default']
    MenuItem: typeof import('./components/Menu/src/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideLeft: typeof import('./components/SideLeft/index.vue')['default']
    SideLeftItem1: typeof import('./components/SideLeft/SideLeftItem1.vue')['default']
    SideLeftItem2: typeof import('./components/SideLeft/SideLeftItem2.vue')['default']
    SideLeftNewArticle: typeof import('./components/SideLeft/SideLeftNewArticle.vue')['default']
    SideRight: typeof import('./components/SideRight/index.vue')['default']
    SubMenu: typeof import('./components/Menu/src/SubMenu.vue')['default']
  }
}
